SimpleVPN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url=settings.DEFAULT_MODULE_REDIRECT)),
]

if settings.ENABLE_DJANGO_ADMIN:
    urlpatterns.append(path('admin/', admin.site.urls))

for module in settings.PLUGIN_MODULES:
    urlpatterns.append(path(module['slug'] + '/',
                            include(f"{module['module_name']}.urls",
                                    namespace=module['namespace'])))

vpn_manager/urls.py
from django.urls import path

from vpn_manager import views

app_name = 'vpn_manager'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('peers', views.ListPeerView.as_view(), name='list_peers'),
    path('peers/add', views.CreatePeerView.as_view(), name='add_peer'),
    path('peers/<int:pk>/delete', views.DeletePeerView.as_view(), name='delete_peer'),
    path('peers/<int:pk>/edit', views.UpdatePeerView.as_view(), name='edit_peer'),
    path('peers/<int:pk>', views.PeerDetailView.as_view(), name='show_peer'),
    path('tools/qrcode', views.QRCodeGeneratorToolTemplateView.as_view(), name='tool_qrcode'),
    path('<slug:token>', views.PeerConfigurationView.as_view(), name='peer_config'),
    path('api/peer/<int:pk>/share', views.PeerShareLinkAPI.as_view(), name='peer_link_api'),
]

vpn_manager/models.py
import secrets

from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

TOKEN_LENGTH = 32


def gen_token():
    return secrets.token_urlsafe(TOKEN_LENGTH)


class ShowConfigLink(models.Model):
    token = models.CharField(max_length=TOKEN_LENGTH,
                             default=gen_token,
                             verbose_name=_("Token"))
    peer = models.OneToOneField('django_wireguard.WireguardPeer',
                                on_delete=models.CASCADE,
                                null=False,
                                related_name='show_config_token',
                                verbose_name=_("WireGuard Peer"))

    class Meta:
        verbose_name = _("Configuration Share Link")
        verbose_name_plural = _("Configuration Share Links")

    def get_link(self, request=None):
        url = reverse_lazy('vpn_manager:peer_config', args=[self.token])
        if request:
            return request.build_absolute_uri(url)
        return str(url)

    def __str__(self):
        return self.get_link()

vpn_manager/forms.py
from ipaddress import IPv4Interface

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django_wireguard.models import WireguardPeer, WireguardInterface


class WireguardPeerForm(forms.ModelForm):
    redirect_traffic = forms.BooleanField(required=False,
                                          initial=True,
                                          help_text=_("Redirect peer traffic through the VPN"))
    killswitch = forms.BooleanField(required=False,
                                    initial=True,
                                    help_text=_("Block all traffic not directed to VPN"))

    class Meta:
        model = WireguardPeer
        fields = ('name', 'public_key', 'redirect_traffic', 'killswitch')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['redirect_traffic'].initial = bool(self.instance.dns)
            self.fields['killswitch'].initial = self.instance.allowed_ips == '0.0.0.0/0'

    def save(self, commit=True):
        self.instance.interface = WireguardInterface.objects.get(name=settings.SIMPLE_VPN_INTERFACE)
        if self.cleaned_data['redirect_traffic']:
            self.instance.dns = settings.SIMPLE_VPN_DNS
            self.instance.allowed_ips = '0.0.0.0/0' if self.cleaned_data['killswitch'] else '0.0.0.0/1,128.0.0.0/1'
        else:
            self.instance.dns = ''
            self.instance.allowed_ips = ','.join(
                str(IPv4Interface(ip).network) for ip in self.instance.interface.get_address_list())

        if self.instance.public_key != self.cleaned_data.get('public_key'):
            # if public_key changed, remove private key
            # if public_key is empty, this code will not be executed (as the cleaned value would be the initial)
            self.instance.private_key = ''

        return super().save(commit)

vpn_manager/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from django_wireguard.models import WireguardPeer

from vpn_manager.forms import WireguardPeerForm
from vpn_manager.models import ShowConfigLink


class IndexView(PermissionRequiredMixin, TemplateView):
    permission_required = 'django_wireguard.view_wireguardpeer'
    template_name = 'vpn_manager/index.html'


class ListPeerView(PermissionRequiredMixin, ListView):
    permission_required = 'django_wireguard.view_wireguardpeer'
    model = WireguardPeer
    template_name = 'vpn_manager/wireguardpeer_list.html'
    context_object_name = 'peers'
    ordering = 'name'
    paginate_by = 5


class CreatePeerView(PermissionRequiredMixin, CreateView):
    permission_required = 'django_wireguard.add_wireguardpeer'
    model = WireguardPeer
    form = WireguardPeerForm
    template_name = 'vpn_manager/wireguardpeer_create.html'
    form_class = WireguardPeerForm
    success_url = reverse_lazy('vpn_manager:list_peers')


class UpdatePeerView(PermissionRequiredMixin, UpdateView):
    permission_required = 'django_wireguard.change_wireguardpeer'
    model = WireguardPeer
    form = WireguardPeerForm
    template_name = 'vpn_manager/wireguardpeer_update.html'
    form_class = WireguardPeerForm
    success_url = reverse_lazy('vpn_manager:list_peers')


class DeletePeerView(PermissionRequiredMixin, DeleteView):
    permission_required = 'django_wireguard.delete_wireguardpeer'
    model = WireguardPeer
    template_name = 'vpn_manager/wireguardpeer_confirm_delete.html'
    context_object_name = 'peer'
    success_url = reverse_lazy('vpn_manager:list_peers')


class PeerDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'django_wireguard.show_wireguardpeer'
    model = WireguardPeer
    template_name = 'vpn_manager/wireguardpeer_detail.html'
    context_object_name = 'peer'


class QRCodeGeneratorToolTemplateView(TemplateView):
    template_name = 'vpn_manager/generate_qrcode_tool.html'


class PeerShareLinkAPI(View):

    def get(self, request, pk):
        try:
            link = ShowConfigLink.objects.get(peer_id=pk)
        except ShowConfigLink.DoesNotExist:
            return HttpResponse(status=404)

        return HttpResponse(link.get_link(request), status=200)

    def post(self, request, pk):
        try:
            peer = WireguardPeer.objects.get(pk=pk)
        except WireguardPeer.DoesNotExist:
            return HttpResponse(status=404)

        link, created = ShowConfigLink.objects.get_or_create(peer=peer)
        return HttpResponse(link.get_link(request), status=201 if created else 200)

    def delete(self, request, pk):
        link = ShowConfigLink.objects.filter(peer_id=pk)
        if not link.exists():
            return HttpResponse(status=404)

        link.delete()
        return HttpResponse(status=204)


class PeerConfigurationView(DetailView):
    model = ShowConfigLink
    template_name = 'vpn_manager/wireguardpeer_detail.html'
    slug_field = 'token'
    slug_url_kwarg = 'token'

    def get_context_data(self, **kwargs):
        context = super(PeerConfigurationView, self).get_context_data(**kwargs)
        context.update({
            'peer': self.object.peer,
        })
        return context

SimpleVPN/templates/_base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block _head_content %}
		<meta charset="UTF-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="{% static 'favicon.ico' %}" rel="icon">
		<title>{% block _title %}{% endblock %}</title>
	{% endblock %}
	{% block _head_css %}
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/main.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block _body_content %}{% endblock %}
	{% block _body_js %}
		<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
	{% endblock %}
</body>
</html>

SimpleVPN/templates/base.html
{% extends "_base.html" %}

{% load static %}
{% load i18n %}

{% block _title %}
	{% block title %}{% endblock %} · {{ app_title }}
{% endblock %}

{% block _head_css %}
	{{ block.super }}
	{% block module_css %}{% endblock %}
{% endblock %}

{% block _body_content %}
	<nav class="navbar navbar-expand-md fixed-top-sm justify-content-start flex-nowrap bg-dark navbar-dark">
		<div class="container">
	    <a href="/" class="navbar-brand">{{ app_title }}</a>
	    <ul class="navbar-nav flex-row ml-2 mr-auto mr-md-0">
		    {% for link in header_links %}
		      <li class="nav-item">
		        <a class="nav-link px-2" href="{{ link.url }}" target="_blank">{{ link.title }}</a>
		      </li>
		    {% endfor %}
	      {% if user.is_authenticated %}
          <li class="nav-item">
		        <a class="nav-link px-2" href="{% url 'logout' %}?next={% url 'login' %}">{% trans "Logout" %}</a>
		      </li>
	      {% endif %}
	    </ul>
			<button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navtabs">
	      <span class="navbar-toggler-icon"></span>
	    </button>
			<div class="navbar-collapse hide collapse pt-2" id="navtabs">
				<ul class="navbar-nav">
		    {% for module in modules %}
		      <li class="nav-item{% if module == current_module %} active{% endif %}">
		        <a class="nav-link" href="{{ module.index }}">{{ module.title }}</a>
		      </li>
			  {% endfor %}
		    </ul>
		  </div>
		</div>
	</nav>
	<nav class="navbar navbar-expand-md bg-dark navbar-dark pb-0 d-none d-md-block">
	  <div class="navbar-collapse collapse pt-2 pt-md-0 container hidden-sm-down">
	    <ul class="nav nav-tabs">
	    {% for module in modules %}
	      <li class="nav-item">
	        <a class="nav-link {% if module == current_module %}active{% else %}text-light{% endif %}" href="{{ module.index }}">{{ module.title }}</a>
	      </li>
		  {% endfor %}
	    </ul>
	  </div>
	</nav>
	<div class="container-fluid py-4">
		{% block module_content %}{% endblock %}
	</div>
{% endblock %}

{% block _body_js %}
	{{ block.super }}
	{% block module_js %}{% endblock %}
{% endblock %}

vpn_manager/templates/vpn_manager/app_base.html
{% extends "base.html" %}
{% load i18n %}

{% block module_css %}
	{% block extra_css %}{% endblock %}
{% endblock %}

{% block title %}{% trans "Manage VPN" %}{% endblock %}

{% block module_content %}
	<div class="container">
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		    <li class="breadcrumb-item"><a href="{{ current_module.index }}">{{ current_module.title }}</a></li>
		    {% block breadcrumb_items %}{% endblock %}
		  </ol>
		</nav>
		<ul class="nav nav-pills mb-4">
		  <li class="nav-item">
		    <a class="nav-link{% if request.resolver_match.url_name == 'index' %} active{% endif %}" href="{% url 'vpn_manager:index' %}">Home</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link{% if request.resolver_match.url_name == 'list_peers' %} active{% endif %}" href="{% url 'vpn_manager:list_peers' %}" id="settings_link">VPN</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link{% if request.resolver_match.url_name == 'tool_qrcode' %} active{% endif %}" href="{% url 'vpn_manager:tool_qrcode' %}" id="settings_link">QRCode Tool</a>
		  </li>
		</ul>
		{% block content %}{% endblock %}
	</div>
	{% block modals %}{% endblock %}
{% endblock %}

{% block module_js %}
	<script type="text/javascript">
		$('.copy-to-clipboard').on('click', function () {
		  let target = $(this).data('target');
		  $(target).select();
		  document.execCommand('copy');
	  })
		$('.download').on('click', function () {
		  let target = $(this).data('target');
		  let data = $(target).text();
		  document.execCommand('copy');
	  });
	</script>
	{% block extra_js %}{% endblock %}
{% endblock %}

vpn_manager/templates/vpn_manager/generate_qrcode_tool.html
{% extends "./app_base.html" %}
{% load django_wireguard_filters %}
{% load static %}
{% load i18n %}
{% load bootstrap_pagination %}

{% block title %}
	{% blocktrans with name=peer.name %}QRCode Tool{% endblocktrans %}
{% endblock %}

{% block breadcrumb_items %}
	<li class="breadcrumb-item">{% trans "Tools" %}</li>
	<li class="breadcrumb-item active" aria-current="page">{% trans "QRCode Generator" %}</li>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-12">
			<h1 class="lead ml-3 mb-5">
				{% blocktrans with name=peer.name %}Generate a QRCode for a WireGuard configuration.{% endblocktrans %}
			</h1>
		</div>
		<div class="col-12 col-md">
			<div class="alert alert-info">{% blocktrans %}<strong class="alert-title">Notice</strong> Data submitted into this form <strong>will not</strong> be uploaded anywhere.{% endblocktrans %}</div>
			<div class="card">
				<div class="card-header">
					{% trans "Text Configuration" %}
				</div>
				<div class="card-body">
					<textarea rows="20" class="form-control" id="config">{{ peer.get_config }}</textarea>
				</div>
				<div class="card-footer">
					<button class="btn btn-primary" onclick="updateQRCode()">
						{% trans "Update" %}
					</button>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-auto mt-5 mt-md-0">
			<div id="qrcode" class="mx-auto"></div>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'js/qrcode.min.js' %}"></script>
	<script type="text/javascript">
			function updateQRCode () {
		    $("#qrcode").empty();
				let qrcode = new QRCode("qrcode", {correctLevel: QRCode.CorrectLevel.L});
				let config = $('#config').val();
				qrcode.makeCode(config);
      }
		  $('#config').on('change', updateQRCode);
	</script>
{% endblock %}

vpn_manager/templates/vpn_manager/index.html
{% extends "./app_base.html" %}
{% load i18n %}

{% block breadcrumb_items %}
	<li class="breadcrumb-item active" aria-current="page">Home</li>
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<h1>Simple VPN</h1>
		<hr />
		<div class="text-justify">
			<p>{% trans "This module lets you manage your VPN connections." %}</p>
		  <a class="btn btn-primary btn-block mt-4" data-toggle="collapse" href="#collapseHelp" role="button" aria-expanded="false" aria-controls="collapseHelp">
		    {% trans "Quick Reference" %}
		  </a>
			<div class="collapse" id="collapseHelp">
				<h5 class="mt-4">{% trans "Creating a peer" %}</h5>
				<hr class="mt-0" />
				<ol>
					<li>{% blocktrans %}Navigate to the <span class="badge badge-primary">VPN</span> panel, then click on <span class="badge badge-primary">New</span>.{% endblocktrans %}</li>
					<li>{% blocktrans %}Fill in the form with a name for this peer (for example, "My Smartphone"){% endblocktrans %}</li>
			    <li>{% blocktrans %}<span class="badge badge-info">Optional</span> for an extra layer of security, provide your own public key. Leave it empty for auto-generation{% endblocktrans %}</li>
					<li>{% blocktrans %}Select <span class="font-weight-bold text-primary">Redirect traffic</span> to forward all traffic through the VPN (standard usage){% endblocktrans %}</li>
					<li>{% blocktrans %}Select <span class="font-weight-bold text-primary">Killswitch</span> if you want any traffic not going through the VPN to be dropped. Uncheck this option to continue accessing your local network (eg. printers, smart devices and such) even when connected to the VPN{% endblocktrans %}</li>
					<li>{% blocktrans %}Click on <span class="badge badge-primary">Save</span>{% endblocktrans %}</li>
				</ol>
				<h5 class="mt-4">{% trans "Downloading configurations" %}</h5>
				<hr class="mt-0" />
				<ol>
					<li>{% blocktrans %}Select the <span class="badge badge-primary">VPN</span> panel{% endblocktrans %}</li>
					<li>{% blocktrans %}From the list, click on the <span class="badge badge-primary">Options</span> button matching the peer you want to see the configuration of, then select <span class="badge badge-secondary">Show Configuration</span> from the menu{% endblocktrans %}</li>
					<li>{% blocktrans %}<span class="badge badge-info">Incomplete configuration</span> if the private key is missing, a warning will be shown. In that case, copy the configuration and replace the private key field manually. You may use the <span class="badge badge-primary">QRCode Tool</span> to generate a convenient valid QR Code{% endblocktrans %}</li>
			    <li>{% blocktrans %}Download the configuration or scan the QR code{% endblocktrans %}</li>
				</ol>
				<h5 class="mt-4">Sharing configurations</h5>
				<hr class="mt-0" />
				<ol>
					<li>{% blocktrans %}Select the <span class="badge badge-primary">VPN</span> panel{% endblocktrans %}</li>
					<li>{% spaceless %}{% blocktrans %}From the list, if the peer has a <span class="badge badge-success">Shared</span> badge, click on it.
If it doesn't, click on the <span class="badge badge-primary">Options</span> button then select <span class="badge badge-secondary">Share</span> from the menu.
You will be asked to create a new link: press on the <span class="badge badge-success">Create link</span> button to do so. The link will then appear, alongside the <span class="badge badge-success">Shared</span> badge.{% endblocktrans %}{% endspaceless %}</li>
			    <li>{% blocktrans %}Copy the link provided and share it.{% endblocktrans %}</li>
					<li>{% blocktrans %}<span class="badge badge-info">Disabling the link</span> you may disable the link anytime.{% endblocktrans %}</li>
				</ol>
			</div>
		</div>
	</div>
{% endblock %}

vpn_manager/templates/vpn_manager/wireguardpeer_confirm_delete.html
{% extends "./app_base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block breadcrumb_items %}
	<li class="breadcrumb-item"><a href="{% url 'vpn_manager:list_peers' %}">{% trans "Peers" %}</a></li>
	<li class="breadcrumb-item"><a href="{% url 'vpn_manager:show_peer' peer.pk %}">{{ peer.name|truncatechars:32 }}</a></li>
	<li class="breadcrumb-item active" aria-current="page">{% trans "Delete" %}</li>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="card">
			<div class="card-header">
				{% blocktrans with name=peer.name %}Confirm deletion of peer <strong>{{ name }}</strong>{% endblocktrans %}
			</div>
			<div class="card-body">
				<div class="alert alert-danger">
					<strong>{% trans "Confirm deletion" %}</strong><br>
					{% spaceless %}{% blocktrans with name=peer.name %}By deleting this peer you will disrupt current connections and invalidate their credentials.
Are you sure you want to delete <strong>{{ name }}</strong>?{% endblocktrans %}{% endspaceless %}
				</div>
				<form method="post">
					{% csrf_token %}
					<button class="btn btn-danger" type="submit" name="submit">{% trans "Confirm" %}</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

vpn_manager/templates/vpn_manager/wireguardpeer_list.html
{% extends "./app_base.html" %}
{% load bootstrap_pagination %}
{% load i18n %}

{% block title %}{% trans "All Peers" %}{% endblock %}

{% block extra_css %}
	<style>
		#share-link {
			background-image: none;
	    padding-right: 10px;
	    background-color: inherit;
		}
	</style>
{% endblock %}

{% block breadcrumb_items %}
	<li class="breadcrumb-item active" aria-current="page">{% trans "Peers" %}</li>
{% endblock %}

{% block content %}
	<div class="card">
		<div class="card-header d-md-flex justify-content-between">
			<h3>{% trans "Peers | Connections" %}</h3>
      <a href="{% url 'vpn_manager:add_peer' %}" class="btn btn-primary d-block d-md-inline-block">{% trans "New" %}</a>
    </div>
    <div class="card-body table-responsive p-0" style="min-height: 200px">
			<table class="table table-borderless{% if peers %} table-hover{% endif %}">
				{% for peer in peers %}
			    <tr>
			      <td>
				      <span class="lead">{{ peer.name }}</span>
			      </td>
			      <td>
				      {{ peer.address }}
			      </td>
			      <td>
				      <a class="badge badge-success share-link" href="javascript:void(0)" data-id="{{ peer.pk }}" {% if not peer.show_config_token %}style="display: none"{% endif %}>
					      {% trans "Shared" %}
				      </a>
			      </td>
				    <td style="text-align: right">
					    <div class="dropdown show">
							  <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="peerOptionsLink{{ peer.pk }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							    {% trans "Options" %}
							  </a>
							  <div class="dropdown-menu" aria-labelledby="peerOptionsLink{{ peer.pk }}" id="peerOptionsDropdown{{ peer.pk }}">
								  <a class="dropdown-item share-link" href="javascript:void(0)" data-id="{{ peer.pk }}">{% trans "Share" %}</a>
								  <a class="dropdown-item" href="{% url 'vpn_manager:show_peer' peer.pk %}">{% trans "Show Configuration" %}</a>
								  <a class="dropdown-item" href="{% url 'vpn_manager:edit_peer' peer.pk %}">{% trans "Edit" %}</a>
								  <a class="dropdown-item text-danger" href="{% url 'vpn_manager:delete_peer' peer.pk %}">{% trans "Delete" %}</a>
							  </div>
							</div>
				    </td>
			    </tr>
				{% empty %}
					<tr>
						<td colspan="3" class="d-flex pt-5">
							<div class="mx-auto lead">{% blocktrans %}No connection. Click on the <span class="text-primary font-weight-bold">New</span> button to start adding connections.{% endblocktrans %}</div>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
		<div class="card-footer">
			{% bootstrap_paginate page_obj %}
		</div>
	</div>
{% endblock %}

{% block modals %}
	<div class="modal fade" id="shareLinkModal" tabindex="-1" role="dialog" aria-labelledby="shareLinkModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title lead" id="shareLinkModalLabel">{% trans "Share Configuration Download Link" %}</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$('#share-link').removeClass('is-valid')">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body p-0">
					<div class="card border-0 mb-0">
						<div class="card-body">
							<div id="link-error">
								<div class="alert alert-danger" id="link-error">{% trans "An error occurred. Please try refreshing the page." %}</div>
							</div>
							<div id="link-spinner">
								<div class="d-flex my-5" id="link-spinner">
									<div class="spinner-grow text-primary mx-auto" role="status">
									  <span class="sr-only">{% trans "Loading" %}</span>
									</div>
								</div>
							</div>
							<div id="link-create">
								<button class="btn btn-block btn-success" id="link-create-btn">{% trans "Create link" %}</button>
							</div>
							<div id="link-show">
								<div class="input-group mb-3">
									<input class="form-control" type="text" id="share-link" readonly />
								  <div class="input-group-append">
								    <button class="btn btn-primary copy-to-clipboard" data-target="#share-link" onclick="$('#share-link').addClass('is-valid')">
									    {% trans "Copy" %}
								    </button>
								  </div>
									<div class="valid-feedback">
						        {% trans "Copied to Clipboard" %}
						      </div>
								</div>
								<button class="btn btn-sm btn-block btn-danger mt-2" id="link-delete-btn">{% trans "Disable Link" %}</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script type="text/javascript">
		const $linkModal = $('#shareLinkModal');
		const $createBtn = $('#link-create-btn');
		const $deleteBtn = $('#link-delete-btn');
		const $linkInput = $('#share-link');
		const $views = {
		  'spinner': $('#link-spinner'),
			'error': $('#link-error'),
			'create': $('#link-create'),
			'show': $('#link-show')
		}
		let peerId;

		function linkView(requestedView) {
		  let found = false;

		  for (let view in $views) {
	      if (view === requestedView) {
          found = true;
          $views[view].show();
	      } else {
	        $views[view].hide();
	      }
		  }
		  if (!found) {
		    $views.error.show();
		  }
		}

		$('.share-link').on('click', function () {
			peerId = $(this).data('id');

			$linkModal.modal('show');

			// use a framework they said, and they might have been right.
			linkView('spinner');

      $.ajax({
        url: formatUrl('{% url "vpn_manager:peer_link_api" 0 %}', peerId),
        method: 'get',
        timeout: 10000,
        success: function (data, status, XHR) {
					$linkInput.val(data);
					linkView('show');
        },
        error: function (request, status, error) {
		      linkView('create');
        }
      });
		});

		$createBtn.on('click', function () {
			$.ajax({
        url: formatUrl('{% url "vpn_manager:peer_link_api" 0 %}', peerId),
        method: 'post',
        timeout: 10000,
        success: function (data, status, XHR) {
					linkView('show');
					$(`.badge[data-id=${peerId}]`).show();
					$linkInput.val(data);
        },
        error: function (request, status, error) {
		      linkView('error');
        }
      });
    });

		$deleteBtn.on('click', function () {
			$.ajax({
	      url: formatUrl('{% url "vpn_manager:peer_link_api" 0 %}', peerId),
	      method: 'delete',
	      timeout: 10000,
	      success: function (data, status, XHR) {
			    $(`.badge[data-id=${peerId}]`).hide();
					linkView('create');
	      },
	      error: function (request, status, error) {
		      linkView('error');
	      }
			});
		});
	</script>
{% endblock %}

vpn_manager/templates/vpn_manager/wireguardpeer_update.html
{% extends "./wireguardpeer_form.html" %}
{% load i18n %}

{% block title %}{% trans "Edit Peer" %}{% endblock %}

{% block breadcrumb_items %}
	<li class="breadcrumb-item"><a href="{% url 'vpn_manager:list_peers' %}">{% trans "Peers" %}</a></li>
	<li class="breadcrumb-item"><a href="{% url 'vpn_manager:show_peer' form.instance.pk %}">{{ form.instance.name|truncatechars:32 }}</a></li>
	<li class="breadcrumb-item active" aria-current="page">{% trans "Edit" %}</li>
{% endblock %}